24

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,90 +1,110 @@
-name: Release Workflow
+name: CI/CD
 
 on:
   push:
-    tags:
-      - 'v*'  # Запускать при создании тегов, начинающихся с v
+    branches:
+      - main
+      - feature/github_actions
 
 jobs:
-
   build-linux:
     runs-on: ubuntu-latest
+    permissions: write-all
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      
-      - name: Build for Linux
-        run: |
-          # Здесь ваши команды для сборки на Linux
-          mkdir appdir
-          echo "Linux build artifact" > appdir/linux-artifact.txt
-          
-      - name: Create Linux artifact  
-        run: |
-          # Создание архива с артефактами для Linux
-          tar -czf linux-artifact.tar.gz -C appdir .
-          
-      - name: Upload Linux artifact
-        uses: actions/upload-artifact@v3
+      - uses: actions/checkout@v3
         with:
-          name: linux-artifact
-          path: linux-artifact.tar.gz
-          
+          submodules: true
+      
+      - run: |
+          sudo apt-get update && sudo apt-get install -y libboost-test-dev libglfw3-dev libglm-dev || { echo 'Failed to install dependencies'; exit 1; }
+      
+      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
+      
+      - run: cmake --build .
+      
+      - run: cmake --build . --target test
+      
+      - run: cmake --build . --target package
+
+      - name: Check if Linux tag exists
+        id: check_tag_exists_linux
+        run: |
+          TAG="release-linux-${{ github.run_number }}-${{ github.sha }}"
+          git tag -l | grep -q "$TAG" && echo "tag_exists=true" >> $GITHUB_ENV || echo "tag_exists=false" >> $GITHUB_ENV
+
+      - name: Create Linux Release
+        id: create_release_linux
+        if: env.tag_exists == 'false'
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: "release-linux-${{ github.run_number }}-${{ github.sha }}"
+          release_name: Linux Release ${{ github.run_number }}
+          draft: false
+          prerelease: false 
+
+      - name: Upload Linux Release Asset 
+        id: upload-release-asset_linux 
+        if: env.tag_exists == 'false'
+        uses: actions/upload-release-asset@v1  
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
+        with:
+          upload_url: ${{ steps.create_release_linux.outputs.upload_url }}  
+          asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.deb  
+          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb  
+          asset_content_type: application/vnd.debian.binary-package 
+
   build-macos:
     runs-on: macos-latest
+    permissions: write-all
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-        
-      - name: Build for macOS
-        run: |  
-          # Здесь ваши команды для сборки на macOS
-          mkdir appdir
-          echo "macOS build artifact" > appdir/macos-artifact.txt
-
-      - name: Create macOS artifact
+      - uses: actions/checkout@v3
+        with:
+          submodules: true
+      
+      - run: |
+          brew update && brew install boost glfw glm || { echo 'Failed to install dependencies'; exit 1; }
+      
+      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
+      
+      - run: cmake --build .
+      
+      - run: cmake --build . --target test
+      
+      - run: cmake --build . --target package
+      
+      - name: Check if macOS tag exists 
+        id: check_tag_exists_macos 
         run: |
-          # Создание архива с артефактами для macOS
-          tar -czf macos-artifact.tar.gz -C appdir .
-          
-      - name: Upload macOS artifact  
-        uses: actions/upload-artifact@v3
-        with:
-          name: macos-artifact
-          path: macos-artifact.tar.gz
+          TAG="release-macos-${{ github.run_number }}-${{ github.sha }}"
+          if git tag -l | grep -q "$TAG"; then
+            echo "tag_exists=true" >> $GITHUB_ENV;
+          else
+            echo "tag_exists=false" >> $GITHUB_ENV;
+          fi
 
-  create-releases:
-    needs: [build-linux, build-macos]
-    runs-on: ubuntu-latest
-    
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-        
-      - name: Download Linux artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: linux-artifact
-        
-      - name: Download macOS artifact  
-        uses: actions/download-artifact@v3
-        with:
-          name: macos-artifact
-        
-      - name: Create Linux Release
-        uses: softprops/action-gh-release@v1
-        with:
-          tag_name: ${{ github.ref }}
-          release_name: Linux Release ${{ github.ref }}
-          files: linux-artifact.tar.gz
+      - name: Create macOS Release
+        id: create_release_macos
+        if: env.tag_exists == 'false'
+        uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          
-      - name: Create macOS Release  
-        uses: softprops/action-gh-release@v1
         with:
-          tag_name: ${{ github.ref }}  
-          release_name: macOS Release ${{ github.ref }}
-          files: macos-artifact.tar.gz
+          tag_name: "release-macos-${{ github.run_number }}-${{ github.sha }}"
+          release_name: macOS Release ${{ github.run_number }}
+          draft: false
+          prerelease: false 
+
+      - name: Upload macOS Release Asset 
+        id: upload-release-asset_macos 
+        if: env.tag_exists == 'false'
+        uses: actions/upload-release-asset@v1  
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
+        with:
+          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}  
+          asset_path: ./helloworld-0.0.${{ github.run_number }}-macOS.pkg  
+          asset_name: helloworld-0.0.${{ github.run_number }}-macOS.pkg  
+          asset_content_type: application/octet-stream 
