36

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,7 +33,7 @@ jobs:
           git tag -l | grep -q "$TAG" && echo "tag_exists=true" >> $GITHUB_ENV || echo "tag_exists=false" >> $GITHUB_ENV
 
       - name: Create Release
-        id: create_release_linux
+        id: create_release
         if: env.tag_exists == 'false'
         uses: actions/create-release@v1
         env:
@@ -45,66 +45,71 @@ jobs:
           prerelease: false 
 
       - name: Upload Release Asset 
-        id: upload_release_asset_linux 
+        id: upload-release-asset 
         if: env.tag_exists == 'false'
         uses: actions/upload-release-asset@v1  
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
         with:
-          upload_url: ${{ steps.create_release_linux.outputs.upload_url }}  
+          upload_url: ${{ steps.create_release.outputs.upload_url }}  
           asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.deb  
           asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb  
           asset_content_type: application/vnd.debian.binary-package 
 
   build-macos:
-    runs-on: macos-latest
-    permissions: write-all
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
+          runs-on: macos-latest
+          permissions: write-all
+          steps:
+            - uses: actions/checkout@v3
+              with:
+                submodules: true
+            
+            - run: |
+                brew update && brew install boost glfw glm || { echo 'Failed to install dependencies'; exit 1; }
+            
+            - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
+            
+            - run: cmake --build .
+            
+            - run: cmake --build . --target test
+            
+            - run: cmake --build . --target package
       
-      - run: |
-          brew update && brew install boost glfw glm || { echo 'Failed to install dependencies'; exit 1; }
-      
-      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
-      
-      - run: cmake --build .
-      
-      - run: cmake --build . --target test
-      
-      - run: cmake --build . --target package
-
-      - name: Check if tag exists for macOS 
-        id: check_tag_exists_macos 
-        run: |
-          TAG="release-${{ github.run_number }}-${{ github.sha }}-macOS"
-          if git tag -l | grep -q "$TAG"; then
-            echo "tag_exists=true" >> $GITHUB_ENV;
-          else
-            echo "tag_exists=false" >> $GITHUB_ENV;
-          fi
-
-      - name: Create macOS Release
-        id: create_release_macos
-        if: env.tag_exists == 'false'
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: "release-${{ github.run_number }}-${{ github.sha }}-macOS"
-          release_name: "macOS Release ${{ github.run_number }}"
-          draft: false
-          prerelease: false 
-
-      - name: Upload macOS Release Asset 
-        id: upload_release_asset_macos 
-        if: env.tag_exists == 'false'
-        uses: actions/upload-release-asset@v1  
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
-        with:
-          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}  
-          asset_path: ./helloworld-0.0.${{ github.run_number }}-macOS.pkg  # macOS-specific file
-          asset_name: helloworld-0.0.${{ github.run_number }}-macOS.pkg  
-          asset_content_type: application/octet-stream
+            # Add this step to list all files generated after the build
+            - name: List files after the build
+              run: ls -alh .
+        
+            - name: Check if tag exists for macOS 
+              id: check_tag_exists_macos 
+              run: |
+                  TAG="release-${{ github.run_number }}-${{ github.sha }}-macOS"
+                  if git tag -l | grep -q "$TAG"; then
+                    echo "tag_exists=true" >> $GITHUB_ENV;
+                  else
+                    echo "tag_exists=false" >> $GITHUB_ENV;
+                  fi
+        
+            - name: Create macOS Release
+              id: create_release_macos
+              if: env.tag_exists == 'false'
+              uses: actions/create-release@v1
+              env:
+                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+              with:
+                tag_name: "release-${{ github.run_number }}-${{ github.sha }}-macOS"
+                release_name: "macOS Release ${{ github.run_number }}"
+                draft: false
+                prerelease: false 
+        
+            - name: Upload macOS Release Asset 
+              id: upload_release_asset_macos 
+              if: env.tag_exists == 'false'
+              uses: actions/upload-release-asset@v1  
+              env:
+                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
+              with:
+                upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
+                asset_path: ./helloworld-0.0.${{ github.run_number }}-macOS.pkg  # Update this path if necessary based on the ls output
+                asset_name: helloworld-0.0.${{ github.run_number }}-macOS.pkg  
+                asset_content_type: application/octet-stream
+        
