10

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: 'C++ CI'
+name: CI/CD
 
 on:
   push:
@@ -7,7 +7,7 @@ on:
       - feature/github_actions
 
 jobs:
-  build_for_ubuntu:
+  build-linux:
     runs-on: ubuntu-latest
     permissions: write-all
     steps:
@@ -15,48 +15,72 @@ jobs:
         with:
           submodules: true
       
-      # Установка необходимых зависимостей
-      - name: Install Dependencies
+      - run: |
+          sudo apt-get update && sudo apt-get install -y libboost-test-dev libglfw3-dev libglm-dev || { echo 'Failed to install dependencies'; exit 1; }
+      
+      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
+      
+      - run: cmake --build .
+      
+      - run: cmake --build . --target test
+      
+      - run: cmake --build . --target package
+
+      - name: Check if tag exists
+        id: check_tag_exists
         run: |
-          sudo apt-get update && \
-          sudo apt-get install -y libboost-test-dev cmake
+          TAG="release-${{ github.run_number }}-${{ github.sha }}"
+          git tag -l | grep -q "$TAG" && echo "tag_exists=true" >> $GITHUB_ENV || echo "tag_exists=false" >> $GITHUB_ENV
 
-      # Конфигурация CMake
-      - name: Configure CMake
-        run: cmake . -DPATCH_VERSION=${{ github.run_number }}
-
-      # Сборка проекта
-      - name: Build Project
-        run: cmake --build .
-
-      # Запуск тестов
-      - name: Run Tests
-        run: cmake --build . --target test
-
-      # Создание пакета
-      - name: Package Project
-        run: cmake --build . --target package
-
-      # Создание релиза на GitHub
       - name: Create Release
         id: create_release
+        if: env.tag_exists == 'false'
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: ${{ github.run_number }}
+          tag_name: "release-${{ github.run_number }}-${{ github.sha }}"
           release_name: Release ${{ github.run_number }}
           draft: false
-          prerelease: false
+          prerelease: false 
 
-      # Загрузка артефактов релиза
-      - name: Upload Release Asset
-        id: upload-release-asset
-        uses: actions/upload-release-asset@v1
+      - name: Upload Release Asset 
+        id: upload-release-asset 
+        if: env.tag_exists == 'false'
+        uses: actions/upload-release-asset@v1  
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
         with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.deb  # Убедитесь, что файл создается правильно
-          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb  # Имя файла для загрузки
-          asset_content_type: application/vnd.debian.binary-package  # Тип контента для DEB-пакета
+          upload_url: ${{ steps.create_release.outputs.upload_url }}  
+          asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.deb  
+          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb  
+          asset_content_type: application/vnd.debian.binary-package 
+
+  build-macos:
+    runs-on: macos-latest
+    permissions: write-all
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: true
+      
+      - run: |
+          brew update && brew install boost glfw glm || { echo 'Failed to install dependencies'; exit 1; }
+      
+      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
+      
+      - run: cmake --build .
+      
+      - run: cmake --build . --target test
+      
+      - run: cmake --build . --target package
+      
+      - name: Check if tag exists for macOS 
+        id: check_tag_exists_macos 
+        run: |
+          TAG="release-${{ github.run_number }}-${{ github.sha }}"
+          if git tag -l | grep -q "$TAG"; then
+            echo "tag_exists=true" >> $GITHUB_ENV;
+          else
+            echo "tag_exists=false" >> $GITHUB_ENV;
+          fi
